# -*- coding: utf-8 -*-

# For testing
FIRST_NAMES = ['Bill', 'Mary', 'Jim', 'Donna', 'Patricia', 
               'Susan', 'Robert', 'Barry', 'Bazza', 'Deena', 
               'Kylie', 'Shane', 'John', 'Michael', 'Anne',
               'Spock', 'Kruskal', 'Platt', 'Klompas', 'Lazarus', 
               'Who', 'Nick', 'Livingston', 'Doolittle', 'Casey', 'Finlay'
               ]


LAST_NAMES = ['Xb', 'Xbal', 'Xbalidocious']


SITES = ['Brookline Ave', 'West Roxbury', 'Matapan', 'Sydney', 'Kansas']
MARITAL_STATUS = ['Single', 'Married', 'Widowed', 'Divorced']
RACES = ['White', 'Black', 'Asian', 'Hispanic', 'Indian', 
         'Native American', 'Alaskan', 'Other','Native Hawaiians','Multiracial']
ETHNICITY = ['Non-Hispanic','Hispanic' ]
STATES = ['MA', 'RI', 'NY', 'CT', 'ME']

CITIES = [ 
    'SOUTH TAMWORTH', 'MIDDLETON', 'GRAPELAND', 'UNCASVILLE', 'W. BOYLSTON', 
    'PROVIDENCE', 'ROCKVILLE', 'EXTON', 'GROTTOES', 'PINE BROOK', 
    'NO FALMOUTH', 'CASPER', 'PAWTUCKET', 'ATHENS', 'NSW', 'BOLINGBROOK', 
    'BOXBOUGH', 'GREAT BARRINGTON', 'EASTBOSTON', 'CENTERDALE', 'SAN CARLOS', 
    'CENTEREACH', 'ST. LOUIS', 'HARWINTON', 'PEEKSKILL', 'NORTHPORT', 
    'BALDWINSVILLE', 'STILL RIVER', 'EAGLE LAKE', 'TEATICKET', 
    'NORTHBRIDGE', 'ALLENSTOWN', 'MARSHFIELD', 'WATERVILLE VALLE', 
    'MATAPAN', 'WALNUT', 'RUSSIA', 'DORCHESTER', 'SKILLMAN', 
    'MOLINE', 'RAYNHAM CENTER', 'NEW YORK CITY', 'URXBRIDGE', 'FRUITPORT', 
    'SPARTANBURG', 'HURST', 'WABAN', 'ORLANDO', 'LAKEVILLE', 'ELLSWORTH', 
    'TURNER''S FALLS', 'RAHWAY', 'WEXFORD', 'OAK HILL', 'BROOKLINE', 
    'DAYTONA BEACH', 'SHAWNEE MISSION', 'WILSON', 'SOTHBORO', 'CAMBRIGDE',
    'LA CRESCENTA', 'ATTLEBORRO', 'N WEYMOUTH','CHELMAFORD', 
    'NORTH HATFIELD', 'WEEMS', 'EAST BRIDGEWATER', 'PROVIDENCE RI', 
    'MORRISTOWN', 'FAIRBURN', 'WOBURN', 'WEST SENECA', 'CLEMMONS', 
    'FORT WAYNE', 'THETFORD', 'NEWTONVILLE', 'MARLBORO MA', 'ST CROIX',
    'MCALLEN', 'DORCESTER', 'BALDWINVILLE', 'YAKIMA', 'S.EASTON', 'ARDMORE',
    'NETHERLANDS', 'GREENLAWN', 'OGDEN', 'N. DIGHTON', 'NO HAVEN', 'WOLLISON',
    'SUMNER', 'NORWWOD', 'WINCHENDON', 'TUCSON', 'RICHMOND HILL', 
    'S. GRAFTON', 'FRAMKLIN', 'CLERMONT', 'LUNENBURG', 'BOSTON'
    ]

ADDRESSES = [
    'COUNTRY FARM RD', 'LOWDEN AVE', 'HIGH ST', 'VINE ST',
    'CLYDE TERR.', 'SHERMAN ST', 'JACKSON TERRACE', 'POND ST',
    'OLD FARM ROAD', 'TRAYER RD', 'SHEPARD ST', 'GROVE ST',
    'CLIFTON RD', 'REVILLA TERRACE', 'WINCHESTER STREET', 
    'CENTRAL ST', 'BENNETT STREET', 'DWIGHT STREET', 
    'GEORGE BROWN STREET', 'WESTVIEW DR', 'BILLINGS AVE', 
    'WHITNEY RD','HOWARD ST', 'BRETTON RD', 'CARLISLE RD',
    'BALOU AVE', 'FERN ST', 'PLEASANT ST', 'MATTAKEESETT ST', 
    'BROOK RD', 'GROVE ST', 'GREENWICH ST', 'EMERALD AVENUE', 
    'BLACKWELL STREET', 'GARVEY RD', 'NIPMUCK DRIVE', 'CENTRAL ST',
    'DONNELLY DR', 'NICHOLAS RD', 'LAKE SHORE ROAD', 'BURLEY ST', 
    'TAUNTON AVE', 'TAURASI RD', 'UMSTEAD HOLLOW PL', 'WHARF ST', 
    'MEADOWS DR', 'FEDERAL WAY', 'VOLUNTEER ROAD', 'ALGONQUIN ROAD',
    'CORDWOOD PATH', 'DELMONT AVENUE', 'WRIGHT FARM RD', 'RANDALL RD',
    'AUDUBON RD', 'CROWDIS ST', 'TREMONT STREET', 'AGREW AVE', 
    'KENNEDY DRIVE', 'CREST ST', 'OLD FARM ROAD', 'SENECA DR.', 
    'BELNAP STREET', 'ASTORIA STREET', 'GROVE STREET', 
    'LITTLETON ROAD', 'BOX 43024', 'UNION ST',
    'CLARK ST', 'HOLDEN STREET', 'SUGAR RD', 'COMMOMWEALTH AVE',
    'PLEASANT STREET', 'CASTLE GREEN ST', 'POPE RD', 
    'HARLOW STREET', 'BEMUTH ROAD', 'HARRISHOF STREET', 
    'W 49TH STREET', 'ANN MARIE DRIVE', 'YORK AVE', 'PEARL ST',
    'GARDNER', 'SNOW CIRCLE', 'CONCORD ST', 'QUEENSBERRY STREET',
    'FLINTLOCK ROAD', 'OCEAN ST', 'COMMONWEALTH AVE', 'MAIN ST',
    'E PROVIDENCE RD', 'DELAWARE AVE', 'MARIE AVE', 
    'TOPICA RD', 'LAUREL HILL LN', 'FOREST ST', 'WHIP O WILL LN', 
    'CEDAR STREET', 'STANLEY AVE', 'ACTON ROAD', 'CASTLE DR'
    ]
