USESQLITE=0
RUNFAKEDATA=0
SITEROOT='/ESP'
LOCALSITE='HVMA' #Prototype' #'HVMA'

MYSQL_DB_USER = 'ESP'
MYSQL_DB_PASSWORD = '3spuser2006'

SQLITE_DB_USER = 'rossSQL'
SQLITE_DB_PASSWORD = 'SQLross'

FTPUSER = 'HEALTHONE\\rlazarus'
FTPPWD = 'Welcome07'
FTPSERVER = 'n2ftp001.hvma.org'


EMAILSENDER='espuser@lkenpesp.healthone.org'
