from django.conf.urls.defaults import *
from django.contrib import admin
from ESP.settings import CODEDIR

urlpatterns = patterns('',
    (r'^images/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '%s/templates' % CODEDIR}),
    (r'^/index/$', 'ESP.esp.views.index'),
    (r'^$', 'ESP.esp.views.index'),
    (r'^/$', 'ESP.esp.views.index'),
    (r'^utilities/$','ESP.esp.views.showutil'),
    (r'^preload/rulexclud/(?P<update>\S*)/$', 'ESP.esp.views.preloadrulexclud'),
    (r'^preload/rulexclud/$', 'ESP.esp.views.preloadrulexclud'),
    (r'^preload/rulexclud/$', 'ESP.esp.views.preloadrulexclud'),
    (r'^preload/(?P<table>\S*)/update/$', 'ESP.esp.views.preloadupdate'),                   
    (r'^preload/(?P<table>\S*)/$', 'ESP.esp.views.preloadview'),
    (r'^cases/sent/(?P<orderby>\S*)/(?P<download>\S*)/$', 'ESP.esp.views.casesent'),
    (r'^cases/sent/(?P<orderby>\S*)/$', 'ESP.esp.views.casesent'),
    (r'^cases/sent/$', 'ESP.esp.views.casesent'),
    (r'^cases/search/$', 'ESP.esp.views.casesearch'),
    (r'^cases/match/(?P<download>\S*)/$', 'ESP.esp.views.casematch'),                       
    (r'^cases/match/$', 'ESP.esp.views.casematch'),
    (r'^cases/define/download/(?P<cpt>\S*)/(?P<component>\S*)/$', 'ESP.esp.views.casedefine_detail'),                 
    (r'^cases/define/detail/$', 'ESP.esp.views.casedefine_detail'),
    (r'^cases/define/(?P<compfilter>\S*)/$', 'ESP.esp.views.casedefine'),
    (r'^cases/define/$', 'ESP.esp.views.casedefine'),
    (r'^cases/search/(?P<inprod>\d+)/$', 'ESP.esp.views.casesearch'),
    (r'^cases/search/(?P<inprod>\d+)/(?P<wf>\S*)/(?P<cfilter>\S*)/(?P<mrnfilter>\S*)/(?P<rulefilter>\S*)/(?P<orderby>\S*)/(?P<download>\S*)/$', 'ESP.esp.views.casesearch'),
    (r'^cases/search/(?P<inprod>\d+)/(?P<wf>\S*)/(?P<cfilter>\S*)/(?P<mrnfilter>\S*)/(?P<rulefilter>\S*)/(?P<orderby>\S*)/$', 'ESP.esp.views.casesearch'),
    (r'^cases/search/(?P<inprod>\d+)/(?P<wf>\S*)/(?P<cfilter>\S*)/(?P<mrnfilter>\S*)/(?P<rulefilter>\S*)/$', 'ESP.esp.views.casesearch'),
    (r'^cases/search/(?P<inprod>\d+)/(?P<wf>\S*)/(?P<cfilter>\S*)/(?P<mrnfilter>\S*)/$', 'ESP.esp.views.casesearch'),                   
    (r'^cases/search/(?P<inprod>\d+)/(?P<wf>\S*)/(?P<cfilter>\S*)/$', 'ESP.esp.views.casesearch'),                   
    (r'^cases/search/(?P<inprod>\d+)/(?P<wf>\S*)/$', 'ESP.esp.views.casesearch'),
                       
    (r'^cases/(?P<object_id>\d+)/updatewf/(?P<newwf>\S*)/$', 'ESP.esp.views.updateWorkflow'),
    (r'^cases/(?P<object_id>\d+)/updatewf/$', 'ESP.esp.views.updateWorkflow'),
    (r'^cases/(?P<inprod>\d+)/(?P<object_id>\d+)/(?P<restrict>\w*)/$', 'ESP.esp.views.casedetail'),
    (r'^pcps/(?P<object_id>\w+)/$', 'ESP.esp.views.pcpdetail'),
    (r'^lx/(?P<object_id>\w+)/$', 'ESP.esp.views.lxdetail'),                  
    (r'^rules/(?P<object_id>\w+)/$', 'ESP.esp.views.ruledetail'),
    (r'^workflows/(?P<object_id>\d+)/$', 'ESP.esp.views.wfdetail'),
    (r'^workflows/(?P<object_id>\d+)/updatewfComment/$', 'ESP.esp.views.updateWorkflowComment'),
    (r'^help/(?P<topic>\w+)/$','ESP.esp.views.showhelp'),
    (r'^help/$','ESP.esp.views.showhelp'),
    (r'^admin/(.*)', admin.site.root),
    (r'^accounts/$', 'django.contrib.auth.views.login'),
    (r'^accounts/login/$', 'django.contrib.auth.views.login'),
    (r'^accounts/logout/$', 'django.contrib.auth.views.logout'),
    (r'^accounts/password_change/$', 'django.contrib.auth.views.password_change', {'template_name': 'registration/password_change_form.html'}),
    (r'^accounts/password_change_done/$', 'django.contrib.auth.views.password_change_done', {'template_name':'registration/password_change_done.html'}),
    (r'^pswdchange/$', 'django.contrib.auth.views.password_change', {'template_name': 'registration/password_change_form.html'}),
    (r'^password_change/$', 'django.contrib.auth.views.password_change', {'template_name': 'registration/password_change_form.html'}),
    (r'^password_change_done/$', 'django.contrib.auth.views.password_change_done', {'template_name': 'registration/password_change_done.html'}),

    (r'^ESP/images/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '%s/templates' % CODEDIR}),
    (r'^ESP//index/$', 'ESP.esp.views.index'),
    (r'^ESP/$', 'ESP.esp.views.index'),
    (r'^ESP//$', 'ESP.esp.views.index'),
    (r'^ESP/utilities/$','ESP.esp.views.showutil'),
    (r'^ESP/preload/rulexclud/(?P<update>\S*)/$', 'ESP.esp.views.preloadrulexclud'),
    (r'^ESP/preload/rulexclud/$', 'ESP.esp.views.preloadrulexclud'),
    (r'^ESP/preload/rulexclud/$', 'ESP.esp.views.preloadrulexclud'),
        

    (r'^ESP/preload/(?P<table>\S*)/update/$', 'ESP.esp.views.preloadupdate'),
    (r'^ESP/preload/(?P<table>\S*)/$', 'ESP.esp.views.preloadview'),
    (r'^ESP/cases/sent/(?P<orderby>\S*)/(?P<download>\S*)/$', 'ESP.esp.views.casesent'),
    (r'^ESP/cases/sent/(?P<orderby>\S*)/$', 'ESP.esp.views.casesent'),
    (r'^ESP/cases/sent/$', 'ESP.esp.views.casesent'),

    (r'^ESP/cases/search/$', 'ESP.esp.views.casesearch'),
    (r'^ESP/cases/match/(?P<download>\S*)/$', 'ESP.esp.views.casematch'),
    (r'^ESP/cases/match/$', 'ESP.esp.views.casematch'),
    (r'^ESP/cases/define/download/(?P<cpt>\S*)/(?P<component>\S*)/$', 'ESP.esp.views.casedefine_detail'),
    (r'^ESP/cases/define/detail/$', 'ESP.esp.views.casedefine_detail'),
    (r'^ESP/cases/define/(?P<compfilter>\S*)/$', 'ESP.esp.views.casedefine'),
    (r'^ESP/cases/define/$', 'ESP.esp.views.casedefine'),
    (r'^ESP/cases/search/(?P<inprod>\d+)/$', 'ESP.esp.views.casesearch'),
    (r'^cases/search/(?P<inprod>\d+)/(?P<wf>\S*)/(?P<cfilter>\S*)/(?P<mrnfilter>\S*)/(?P<rulefilter>\S*)/(?P<orderby>\S*)/(?P<download>\S*)/$', 'ESP.esp.views.casesearch'),
    (r'^ESP/cases/search/(?P<inprod>\d+)/(?P<wf>\S*)/(?P<cfilter>\S*)/(?P<mrnfilter>\S*)/(?P<rulefilter>\S*)/(?P<orderby>\S*)/$', 'ESP.esp.views.casesearch'),
    (r'^ESP/cases/search/(?P<inprod>\d+)/(?P<wf>\S*)/(?P<cfilter>\S*)/(?P<mrnfilter>\S*)/(?P<rulefilter>\S*)/$', 'ESP.esp.views.casesearch'),
    (r'^ESP/cases/search/(?P<inprod>\d+)/(?P<wf>\S*)/(?P<cfilter>\S*)/(?P<mrnfilter>\S*)/$', 'ESP.esp.views.casesearch'),
    (r'^ESP/cases/search/(?P<inprod>\d+)/(?P<wf>\S*)/(?P<cfilter>\S*)/$', 'ESP.esp.views.casesearch'),
    (r'^ESP/cases/search/(?P<inprod>\d+)/(?P<wf>\S*)/$', 'ESP.esp.views.casesearch'),

    (r'^ESP/cases/(?P<object_id>\d+)/updatewf/(?P<newwf>\S*)/$', 'ESP.esp.views.updateWorkflow'),
    (r'^ESP/cases/(?P<object_id>\d+)/updatewf/$', 'ESP.esp.views.updateWorkflow'),
    (r'^ESP/cases/(?P<inprod>\d+)/(?P<object_id>\d+)/(?P<restrict>\w*)/$', 'ESP.esp.views.casedetail'),
    (r'^ESP/pcps/(?P<object_id>\w+)/$', 'ESP.esp.views.pcpdetail'),
    (r'^ESP/lx/(?P<object_id>\w+)/$', 'ESP.esp.views.lxdetail'),
    (r'^ESP/rules/(?P<object_id>\w+)/$', 'ESP.esp.views.ruledetail'),
    (r'^ESP/workflows/(?P<object_id>\d+)/$', 'ESP.esp.views.wfdetail'),
    (r'^ESP/workflows/(?P<object_id>\d+)/updatewfComment/$', 'ESP.esp.views.updateWorkflowComment'),
    (r'^ESP/help/(?P<topic>\w+)/$','ESP.esp.views.showhelp'),
    (r'^ESP/help/$','ESP.esp.views.showhelp'),
    (r'^ESP/admin/(.*)', admin.site.root),
    (r'^ESP/accounts/$', 'django.contrib.auth.views.login'),
    (r'^ESP/accounts/login/$', 'django.contrib.auth.views.login'),
    (r'^ESP/accounts/logout/$', 'django.contrib.auth.views.logout'),

    (r'^ESP/accounts/password_change/$', 'django.contrib.auth.views.password_change', {'template_name': 'registration/password_change_form.html'}),
    (r'^ESP/accounts/password_change_done/$', 'django.contrib.auth.views.password_change_done', {'template_name':'registration/password_change_done.html'}),
    (r'^ESP/password_change/$', 'django.contrib.auth.views.password_change', {'template_name': 'registration/password_change_form.html'}),
    (r'^ESP/password_change_done/$', 'django.contrib.auth.views.password_change_done', {'template_name': 'registration/password_change_done.html'}),
    (r'^ESP/pswdchange/$', 'django.contrib.auth.views.password_change', {'template_name': 'registration/password_change_form.html'}),
)


