'''
                                  ESP Health
                         Notifiable Diseases Framework
                            alternative mappings

@author: Bob Zambarano <bzambarano@commoninf.com>
@organization: Commonwealth informatics http://www.commoninf.com
@copyright: (c) 2014 Commonwealth Informatics
@license: LGPL - http://www.gnu.org/licenses/lgpl-3.0.txt

--------------------------------------------------------------------------------
'''

#---------------------------
# assumes 
ALTCODEMAPPING = {'patient.race':         {'W1': ['W','White','L','4'],
                                           'W2': ['WH','White','L',''],
                                           'W3': ['W','White','L',''],
                                           'W4': ['','','',''],
                                           'W5': ['wh','white','L',''],
                                           'W6': ['Wh','White','L',''],
                                           'W7': ['W','White','L',''],
                                           'W8': ['w','White','L',''],
                                           'B1': ['B','Black or African American','L',''],
                                           'A1': ['A','Asian','L','4'],
                                           'A2': ['','','',''],
                                           'A3': ['A','Asian','L',''],
                                           'AI': ['AN','American Native','L',''],
                                           'I1': ['PI','Pacific Islander','L',''],
                                           'I2': ['P','Pacific Islander','L',''],
                                           '': ['','','',''],
                                           None: ['','','',''],
                                          },
                  'patient.ethnicity':   {'NH1': ['NH','Non hispanic','L','4'],
                                          'H1': ['L','Latino','L',''],
                                          'H2': ['L','Latino','L',''],
                                          'H3': ['L','Latino','L','4'],
                                          'NH2': ['NL','not latino','L',''],
                                          'NH3': ['NH','','L',''],
                                          'NH4': ['','','',''],
                                          'NH5': ['NH','Not Hispanic or Latino','L',''],
                                          'NH6': ['','','',''],
                                           '': ['','','',''],
                                           None: ['','','',''],
                                          },
                  'patient.species':      {'Homo sapiens (organism)': ['human','human','L','4'],
                                           '': ['','','',''],
                                           None: ['','','',''],
                                           },
                  'patient_guardian.relationship': {'Guardian': ['LG','Legal Guardian','L','3'],
                                                    'Mother': ['M','Mother','L','4.1'],
                                                    'Spouse': ['S','Spouse','L','40544'],
                                           '': ['','','',''],
                                           None: ['','','',''],
                                          },
                  'laborder.procedure_code': {'5671-3': ['PB','lead blood','L','1.2'],
                                              '5609-3': ['CAD-01','Cadmium Blood','L',''],
                                              '625-4': ['3456543','CULTURE STOOL','99USI',''],
                                              '625-4_1': ['3456543','CULTURE STOOL','99USI',''],
                                              '50545-3': ['Bact suscept','Bacteria susceptibility','99USI',''],
                                              'AHEPR': ['','','',''],
                                              '6812-2': ['3752','Dengue Fever - IGM AB EIA','L','v1'],
                                              '64017-7': ['2332','APTIMA GC/CT Panel','L',''],
                                              '6463-4': ['TCX','Throat Culture','L',''],
                                              '11011-4': ['HCVRNA','Hepatitis C RNA PCR','L',''],
                                              '23826-1': ['BPRP','Bordetella pertussis PCR','L',''],
                                              '11475-1': ['CXCSF','Cerebrospinal Fluid (CSF) Culture','L',''],
                                              '1742-6': ['SALT','Serum ALT','L','1.2'],
                                              '24467-3': ['2153','ABSOLUTE CD4+ CELLS','L','1.2'],
                                              '29579-0': ['SIRE','MTB Susceptibility Panel (SIRE)','L',''],
                                              '31147-2': ['2059','Syphilis RPR','L','v45'],
                                              '33331-0': ['1522','West Nile virus AB IgM, ELISA, Serum','L',''],
                                              '40699-1': ['AFBID','AFB Identification','L',''],
                                              '40982-1': ['FBPCR','Flu B PCR','L',''],
                                              '46197-0': ['ROP','Rubeola (Measles) Antibodies, IgG and IgM (Separate Determinations), Serum','L',''],
                                              '48174-7': ['MTBN','MTB complex NAAT','L',''],
                                              '51657-5': ['137','HCV Profile','L',''],
                                              '543-9': ['AFBC','AFB Culture','L',''],
                                              '60566-7': ['2007','Luminex Multiplex Respiratory Virus PCR','L',''],
                                              '': ['','','',''],
                                           None: ['','','',''],
                                          },
                  'laborder.reason_code': {'V1586': ['LEAD','Lead exposure','L','V1'],
                                           '5733': ['Hepatitis','Hepatitis','L','V1'],
                                           '042': ['HIV','HIV/Aids','L','V1'],
                                           '': ['','','',''],
                                           None: ['','','',''],
                                          },
                  'labresult.native_code': {'--5671-3': ['PB','lead blood','L','V1'],
                                            '--5609-3': ['CaBL','Blood Cadmium','L',''],
                                            '--625-4': ['StlC','Stool culture','99USI',''],
                                            '--625-4_1': ['Bacteria identified','Bacteria identified','99USI',''],
                                            '--20-8': ['AmoxClav','Amoxicillin-clavulanic acid','99USI',''],
                                            '--516-5': ['TMP-SMX','Trimethoprim-sulfamethoxazole','99USI',''],
                                            '--185-9': ['CIPROFLOXACIN','CIPROFLOXACIN','99USI',''],
                                            '--22314-9': ['HAVM','Hepatitis A IgM antibodies (IgM anti-HAV)','L',''],
                                            '--16933-4': ['HBVcAB','Hepatitis B core antibodies (anti-HBVc)','L',''],
                                            '--5195-3': ['HBVsAG','Hepatitis B surface antigen (HBsAg)','L',''],
                                            '--13955-0': ['HCVAB','Hepatitis C antibody screen  (anti-HCV)','L',''],
                                            '--48159-8': ['HCVSCO','Hepatitis C antibodies Signal to Cut-off Ratio','L',''],
                                            '--11011-4': ['HCVRNA','Hepatitis C RNA PCR','L',''],
                                            '--6812-2': ['3752','Dengue Fever - IGM AB EIA','L','v1'],
                                            '--43305-2': ['2334','APTIMA GC','L',''],
                                            '--43304-5': ['2336','APTIMA CT','L',''],
                                            '--6463-4': ['TCX','Throat Culture','L',''],
                                            '--23826-1': ['BPRP','Bordetella pertussis PCR','L',''],
                                            '--108-1': ['CTX','CEFOTAXIME','L',''],
                                            '--11475-1': ['CXCSF','Cerebrospinal Fluid (CSF) Culture','L',''],
                                            '--141-2': ['CAX','CEFTRIAXONE','L',''],
                                            '--145-3': ['CXMP','CEFUROXIME, SODIUM','L',''],
                                            '--1742-6': ['SALT','Serum ALT','L','1.2'],
                                            '--193-3': ['CC','CLINDAMYCIN','L',''],
                                            '--20396-8': ['LVX','LEVOFLOXACIN','L',''],
                                            '--20479-2': ['ROG','Rubeola (Measles) Ab, IgG, S','L',''],
                                            '--21503-8': ['ROM','Rubeola (Measles) Ab, IgM, S','L',''],
                                            '--233-7': ['E','RYTHROMYCIN','L',''],
                                            '--24467-3': ['2153','ABSOLUTE CD4+ CELLS','L','1.2'],
                                            '--25194-2': ['ETHA','Ethambutol 5.0 ug/mL','L',''],
                                            '--25202-3': ['RIFA','Rifampin 1.0 ug/mL','L',''],
                                            '--25217-1': ['ISON','Isoniazid 0.1 ug/mL','L',''],
                                            '--29908-1': ['Para 1 (NAT)','Para Influenza Virus 1 (NAT)','L',''],
                                            '--29909-9': ['Para 2 (NAT)','Para Influenza Virus 2 (NAT)','L',''],
                                            '--29910-7': ['Para 3 (NAT)','Para Influenza Virus 3 (NAT)','L',''],
                                            '--30075-6': ['RSV A (NAT)','RSV A (NAT)','L',''],
                                            '--30076-4': ['RSV B (NAT)','RSV B (NAT)','L',''],
                                            '--31147-2': ['2059','Syphilis RPR','L','v45'],
                                            '--33331-0': ['1522','West Nile virus AB IgM, ELISA, Serum','L',''],
                                            '--34487-9': ['Influenza A (NAT)','Influenza A (NAT)','L',''],
                                            '--38917-1': ['Metapneumo (NAT)','Metapneumovirus (NAT)','L',''],
                                            '--39528-5': ['Adenovirus (NAT)','Adenovirus (NAT)','L',''],
                                            '--40982-1': ['Influenza B (NAT)','Influenza B (NAT)','L',''],
                                            '--48174-7': ['MTBN','MTB complex NAAT','L',''],
                                            '--48177-0': ['STRP','Streptomycin 1.0 ug/mL','L',''],
                                            '--49521-8': ['Influenza A/H1 (NAT)','Influenza A/H1 (NAT)','L',''],
                                            '--49524-2': ['Influenza A/H3 (NAT)','Influenza A/H3 (NAT)','L',''],
                                            '--524-9': ['VA','VANCOMYCIN','L',''],
                                            '--543-9': ['AFBC','AFB Culture','L',''],
                                            '--6644-9': ['FEP','CEFEPIME','L',''],
                                            '--6652-2': ['MEM','MEROPENEM','L',''],
                                            '--6932-8': ['PEN','Penicillin','L',''],
                                            '--7993-9': ['RhinoVirus (NAT)','RhinoVirus (NAT)','L',''],
                                            '': ['','','',''],
                                           None: ['','','',''],
                                          },
                  'labresult.char_finding': {'Campylobacter jejuni': ['','','',''],
                                             'Shigella flexneri': ['','','',''],
                                             'Shigella flexneri 2': ['','','',''],
                                             'Negative (qualifier value)': ['NEG','NEGATIVE','L',''],
                                             'Positive (qualifier value)': ['POS','POSITIVE','L',''],
                                             'Corynebacterium diphtheriae': ['','','',''],
                                             'Positive2': ['BPPOS','Positive','L',''],
                                             'Positive3': ['POS','Positive','L',''],
                                             'Salmonella species (organism)': ['Salm','Salmonella species','L',''],
                                             'Not detected (qualifier value)': ['Not Detected','Not Detected','L',''],
                                             'Reactive': ['R','Reactive','L',''],
                                             'Haemophilus influenzae (organism)': ['H inf','Haemophilus influenzae','L',''],
                                             'Mycobacterium tuberculosis complex (organism)': ['','','',''],
                                             'Staphylococcus aureus (organism)': ['S aureus','Staphylococcus aureus','L',''],
                                             'Reactive (qualifier value)': ['REACT','Reactive','L',''],
                                             'Detected': ['Det','detected','L',''],
                                             'Mycobacterium avium': ['Mycobacterium avium','Mycobacterium avium','L',''],
                                             'Neisseria meningitidis': ['Neisseria meningitid','Neisseria meningitidis','L',''],
                                             'Escherichia coli (organism)': ['E coli','Escherichia coli','L',''],
                                             'Streptococcus pneumoniae (organism)': ['','','',''],
                                             'Detected (qualifier value)': ['Detected','Detected','L',''],
                                           '': ['','','',''],
                                           None: ['','','',''],
                                             },
                  'labresult.ref_unit': {'ug/dL': ['ug/dl','microgram per deciliter','L','V1'],
                                         'ug/L': ['','','',''],
                                         'ug/mL': ['','','',''],
                                         '{s_co_ratio}': ['s/co','','L',''],
                                         '[IU]/mL': ['IU/ml','','L',''],
                                         '{titer}': ['titer','titer','L',''],
                                         "[arb'U]": ['growth units','growth units','L',''],
                                         '{Cells}/uL': ['cells/mcL','cells per microliter','L','V1'],
                                         'U/L': ['U/L','Units per liter','L','V1'],
                                           '': ['','','',''],
                                           None: ['','','',''],
                                          },
                  'labresult.abnormal_flag': {'H': ['H','High','L','V1'],
                                           'H1': ['','','',''],
                                           'H2': ['','','',''],
                                           'I': ['','','',''],
                                           'R': ['','','',''],
                                           'S': ['','','',''],
                                           'A': ['','','',''],
                                           'L': ['L','Low','L','V1'],
					   'LL': ['','','',''],
                                           '': ['','','',''],
                                           None: ['','','',''],
                                          },
                  'labresult.lab_method': {'Atomic Absorption Spectrophotometry': ['ETAAS','Electrothermal Atomic Absorption Spectrophotometry','L','V1'],
                                           'Flow Cytometry (FC)': ['FC','Flow Cytometry','L','V1'],
                                           'Spectrophotometry': ['ALTMETHOD','Photometric rate, L-alanine with Pyridoxal -5- Phosphate','L','V1'],
                                           '': ['','','',''],
                                           None: ['','','',''],
                                           },
                  'labresult.comment': {'R': ['','','',''],
                                           '': ['','','',''],
                                           None: ['','','',''],
                                        },
                  'specimen.specimen_source': {'Capillary Blood Specimen': ['CAPF','Capillary, filter paper card','L','v1'],
                                               'Capillary Blood 2': ['BLDC','Blood, Capillary','L',''],
                                               'Venous Blood Specimen': ['BV-CAD','Venous Cadmium Test','L',''],
                                               'Stool specimen1': ['Stl','Stool','L',''],
                                               'Stool specimen2': ['','','',''],
                                               'Microbial isolate specimen': ['','','',''],
                                               'Serum specimen (specimen)': ['SER','Serum','L',''],
                                               'Serum specimen 2': ['','','',''],
                                               'Serum specimen 3': ['SER','Serum','L','40939'],
                                               'Serum specimen 4': ['SER','Serum','L',''],
                                               'Urine specimen (specimen)': ['Urine','Urine','L',''],
                                               'Throat swab (specimen)': ['THS','Throat swab','L',''],
                                               'Nasopharyngeal swab': ['NPS','Nasopharyngeal Swab','L',''],
                                               'Blood specimen (specimen)': ['BLD','Blood','L',''],
                                               'Cerebrospinal fluid sample (specimen)': ['CSF','Cerebrospinal Fluid','L',''],
                                               'Sputum specimen (specimen)': ['SPU','Sputum','L',''],
                                               'Swab of internal nose (specimen)': ['Nasal swab','Nasal swab','L',''],
                                               'Whole blood sample (specimen)': ['BLD','Whole Blood EDTA','L','40939'],
                                               'Wound swab (specimen)': ['WND','WOUND','L',''],
                                           '': ['','','',''],
                                           None: ['','','',''],
                                          },
                  'specimen.type_modifier': {'Morning (qualifier value)': ['AM','A.M. sample','L','40939'],
                                             'Venous (qualifier value)': ['Ven','Venous','L','40939'],
                                           '': ['','','',''],
                                           None: ['','','',''],
                                           }, 
                  'specimen.additives': {'none': ['NA','No Additive','L','V1'],
                                         'Potassium/K EDTA': ['LT','Lavender top tube','L','V1'],
                                         'Serum Separator Tube': ['ST','Serum Separator Tube','L','V1'],
                                           '': ['','','',''],
                                           None: ['','','',''],
                                          },
                  'specimen.collection_method': {'Capillary Specimen Collection (procedure)': ['CAPF','Capillary, filter paper card','L','V1'],
                                                 'Venipuncture': ['VEN','Venous','L',''],
                                                 'Capillary Specimen': ['CB','Cap blood','L',''],
                                                 'Collection of blood specimen for laboratory (procedure)': ['VBD','Venous Blood Draw','L','V1'],
                                                 '': ['','','',''],
                                                 None: ['','','',''],
                                          },
                  'specimen.source_site': {'Finger structure (body structure)': ['FIL','Finger, Left','L','V1'],
                                           'Antecubital fossa': ['ELBL','Elbow, Left','L','V1'],
                                           '': ['','','',''],
                                           None: ['','','',''],
                                          },
                  'specimen.source_site_modifier': {'Left (qualifier value)': ['FIL','Finger, Left','L','V1'],
                                           '': ['','','',''],
                                           None: ['','','',''],
                                          },
                  'specimen.specimen_role': {'Patient': ['P','Patient','L','V1'],
                                           '': ['','','',''],
                                           None: ['','','',''],
                                          },
                  'specimen.amount_id': {'Number': ['unit','unit','L','V1'],
                                         'milliliter': ['ml','ml','L','V1'],
                                           '': ['','','',''],
                                           None: ['','','',''],
                                          },
                  'specobs.type': {'Age at Specimen Collection': ['AGE','AGE','L','V1'],
                                           '': ['','','',''],
                                           None: ['','','',''],
                                          },
                  'specobs.unit': {'Year': ['Y','Years','L','V1'],
                                           '': ['','','',''],
                                           None: ['','','',''],
                                   },}
