#!/usr/bin/python
# -*- coding: utf-8 -*-

GOOGLE_MAPS_KEY = 'ABQIAAAANYaWiQCeHxdzuZxZyFm9SBTFXQrzfCP8K9ly-DAQQbVGbYS8dBSHJdZDDgpj5Nwjb6VuGOhKvZwP2g'
MAP_CENTER_LATITUDE = 42.40
MAP_CENTER_LONGITUDE = -71.25
MAP_ZOOM_LEVEL = 10




GIPSE_REQUESTING_USER = 'Tester'
